import type { Metadata } from 'next'
import './globals.css'
import './cart.css'
import './menu.css'
import './order.css'
import './end.css'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        {children}
        </body>
    </html>
  )
}
